# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Digital_Clock_XDC.xdc

# Block Designs: bd/Digital_Clock/Digital_Clock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock || ORIG_REF_NAME==Digital_Clock} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_clk_wiz_0_0/Digital_Clock_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_clk_wiz_0_0 || ORIG_REF_NAME==Digital_Clock_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_clk_div_0_0/Digital_Clock_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_clk_div_0_0 || ORIG_REF_NAME==Digital_Clock_clk_div_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_cnt10_0_0/Digital_Clock_cnt10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_cnt10_0_0 || ORIG_REF_NAME==Digital_Clock_cnt10_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_cnt6_0_1/Digital_Clock_cnt6_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_cnt6_0_1 || ORIG_REF_NAME==Digital_Clock_cnt6_0_1} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_cnt10_0_1/Digital_Clock_cnt10_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_cnt10_0_1 || ORIG_REF_NAME==Digital_Clock_cnt10_0_1} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_cnt6_0_2/Digital_Clock_cnt6_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_cnt6_0_2 || ORIG_REF_NAME==Digital_Clock_cnt6_0_2} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_display_0_0/Digital_Clock_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_display_0_0 || ORIG_REF_NAME==Digital_Clock_display_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_display_0_1/Digital_Clock_display_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_display_0_1 || ORIG_REF_NAME==Digital_Clock_display_0_1} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_xlconstant_0_0/Digital_Clock_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_xlconstant_0_0 || ORIG_REF_NAME==Digital_Clock_xlconstant_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_xlconstant_1_0/Digital_Clock_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_xlconstant_1_0 || ORIG_REF_NAME==Digital_Clock_xlconstant_1_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_xlconstant_2_0/Digital_Clock_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_xlconstant_2_0 || ORIG_REF_NAME==Digital_Clock_xlconstant_2_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_xlconstant_3_0/Digital_Clock_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_xlconstant_3_0 || ORIG_REF_NAME==Digital_Clock_xlconstant_3_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_xlconcat_0_0/Digital_Clock_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_xlconcat_0_0 || ORIG_REF_NAME==Digital_Clock_xlconcat_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_Mux2to1_DF_0_0/Digital_Clock_Mux2to1_DF_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_Mux2to1_DF_0_0 || ORIG_REF_NAME==Digital_Clock_Mux2to1_DF_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_clk_out_0_0/Digital_Clock_clk_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_clk_out_0_0 || ORIG_REF_NAME==Digital_Clock_clk_out_0_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_Mux2to1_DF_1_0/Digital_Clock_Mux2to1_DF_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_Mux2to1_DF_1_0 || ORIG_REF_NAME==Digital_Clock_Mux2to1_DF_1_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_Mux2to1_DF_2_0/Digital_Clock_Mux2to1_DF_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_Mux2to1_DF_2_0 || ORIG_REF_NAME==Digital_Clock_Mux2to1_DF_2_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_clk_out_1_0/Digital_Clock_clk_out_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_clk_out_1_0 || ORIG_REF_NAME==Digital_Clock_clk_out_1_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_clk_out_2_0/Digital_Clock_clk_out_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_clk_out_2_0 || ORIG_REF_NAME==Digital_Clock_clk_out_2_0} -quiet] -quiet

# IP: bd/Digital_Clock/ip/Digital_Clock_cnt24_0_1/Digital_Clock_cnt24_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Digital_Clock_cnt24_0_1 || ORIG_REF_NAME==Digital_Clock_cnt24_0_1} -quiet] -quiet

# XDC: bd/Digital_Clock/Digital_Clock_ooc.xdc
